AZURE_OPENAI_ENDPOINT = "https://YOUR-RESOURCE.openai.azure.com/"
AZURE_OPENAI_API_KEY = "YOUR_API_KEY"
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o"

MODEL_NAME = "gpt-4o"
MAX_MODEL_TOKENS = 128000
SAFETY_MARGIN = 2000  # buffer for output tokens
